### ISSUE TITLE
Dependency on eea.rdfmarshaller in eea.versions prevents eea.daviz from installing

### ISSUE THREAD

**Issue by fredvd** [eea/eea.versions#1]
eea.versions is a dependency of eea.daviz.  when installing eea.daviz, eea.versions now has a dependency on eea.rdmarshaller, but this package is not present on pypi, it's only published on http://eggrepo.apps.eea.europa.eu/d/eea.rdfmarshaller/ and as source available on github.

**Comment by avoinea** [comment]
I will drop the hard dependency on eea.rdfmarhaller.

**Comment by fredvd** [comment]
I don't know how necessary it is for extra functionality, you know that much better. Does it add something to daviz? Pushing rdfmarshaller to pypi is also an option. :-) but yet another package to pull in for daviz installation,  but thats big enough already.

**Comment by avoinea** [comment]
Dropped eea.rdfmarshaller hard dependency. See https://pypi.python.org/pypi/eea.versions/9.4
